docs: added more comprehensive react example
ivanhofer/typesafe-i18n pull request #565
Opened 2023-01-12 19:20 UTC by beqaMeqvabishvili

Currently, it's really easy to miss single line comment `// TODO: load locales` in the react example. This PR adds a basic example of detecting and loading locales in a standard react app.

2023-01-13 07:44 UTC, ivanhofer requested changes
Thanks for taking the initiative. Here are two small improvements

2023-01-13 07:44 UTC, ivanhofer commented on packages/adapter-react/README.md
> +   const locale = detectLocale(
You can use the `detectLocale` function from `i18n/i18n-util.ts`. Then you don't need to pass `baseLocale` and `locales`

2023-01-13 07:44 UTC, ivanhofer commented on packages/adapter-react/README.md
> +import { detectLocale, navigatorDetector } from 'typesafe-i18n/detectors';
please get rid of all semi-colons (`;`) to match the style of all other examples

2023-01-14 14:17 UTC, beqaMeqvabishvili commented
Hey! updated the PR as you requested and then I took a liberty to remove `import React from 'react'` from the example I worked on and also everywhere else in the docs - it's no longer necessary after v17 release in 2020

2023-01-15 06:36 UTC, ivanhofer approved these changes

2023-01-15 06:37 UTC, ivanhofer commented
> I took a liberty to remove `import React from 'react'` from the example

Oh thanks. I didn't knew that!

2023-01-15 06:43 UTC, ivanhofer commented
Thanks for the fixes!

2023-01-15 06:43 UTC, merged